name: prediction-ai
channels:
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.7.0
  - aom=3.6.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - click=8.2.1
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - fastapi=0.112.2
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - graphite2=1.3.14
  - h11=0.16.0
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - ipykernel=6.29.5
  - ipython=8.15.0
  - jedi=0.19.2
  - joblib=1.5.1
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libcxx=19.1.7
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.2
  - libiconv=1.16
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - llvm-openmp=19.1.7
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numexpr=2.11.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.17
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pyparsing=3.2.0
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyzmq=26.2.0
  - readline=8.3
  - scikit-learn=1.7.1
  - scipy=1.15.3
  - seaborn=0.13.2
  - setuptools=78.1.1
  - six=1.17.0
  - sniffio=1.3.0
  - sqlite=3.50.2
  - stack_data=0.2.0
  - starlette=0.38.2
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - unicodedata2=15.1.0
  - uvicorn=0.35.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - xgboost==3.1.2